import { Inter } from "next/font/google";
import Footer from "./_components/Footer/footer";
import Navbar  from "./_components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-[100vh]`}>
      <Navbar />
        <div className="flex-1 h-full">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
